name: CI DEV
on:
  pull_request:
    branches:
      - dev
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Tags
        run: git tag

      - name: Semantic Versioning
        id: versioning
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          short_tags: false
          major_pattern: "/^BREAKING CHANGE:/"
          minor_pattern: "/^feat:/"
          format: "${major}.${minor}.${patch}"

      - name: Print Output
        run: echo 'version is ${{ steps.versioning.outputs.version }}  \n  tag version is ${{ steps.versioning.outputs.version_tag }}'

      - name: Create Tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.versioning.outputs.version_tag}}',
              sha: context.sha
            })

#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle set version
        run: ./gradlew -Dversion.semver=${{steps.versioning.outputs.version}}

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "update semantic version" -a
          git push origin HEAD:${{ github.ref }}


